---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hultetvsf-app.fullname" . }}-token-updater
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hultetvsf-app.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hultetvsf-app.fullname" . }}-token-secret-updater
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hultetvsf-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ include "hultetvsf-app.fullname" . }}-google-credentials"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hultetvsf-app.fullname" . }}-token-updater-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hultetvsf-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hultetvsf-app.fullname" . }}-token-secret-updater
subjects:
- kind: ServiceAccount
  name: {{ include "hultetvsf-app.fullname" . }}-token-updater
  namespace: {{ .Release.Namespace }}
