apiVersion: v2
name: hultetvsf-app
description: A Helm chart to deploy the hultetvsf app (Express server with Google Drive integration)
type: application
version: 0.1.69-7eee4f14
appVersion: "7eee4f14"
keywords:
  - hultetvsf
  - web
  - static
maintainers:
  - name: hultetvsf
    email: devnull@example.com
